#!/bin/sh
#              $Id$

# (C) 2001 by the Board of Trustees of the Leland Stanford, Jr., University
#                          All Rights Reserved
# Produced by Andrew Hanushevsky for Stanford University under contract
#            DE-AC03-76-SFO0515 with the Deprtment of Energy

# Establish things we will look for
#
AFSFS=/usr/afsws/bin/fs
UNAME=/bin/uname
VERBOSE=0

##############################################################################
#                           s u b r o u t i n e s                            #
##############################################################################

Debug () {
    if test $VERBOSE -eq 1; then
       /bin/echo $1
    fi
    }
  
FileThere () {
    Debug "Checking file $2 ..."
    if /usr/bin/test -${1} $2; then
       return 0
    fi
    return 1
    }

##############################################################################
#                          m a i n   p r o g r a m                           #
##############################################################################

# If the AFS fs command exists, then this becomes the system name
#
    if FileThere x $AFSFS; then
       SYSNAME=`$AFSFS sysname | /bin/awk -F\' '{print $2}'`
  elif FileThere x $UNAME; then
       OSNAME=`$UNAME`
       RLNAME=`$UNAME -r`
       MTNAME=`$UNAME -m`
       if [ $OSNAME = SunOS ]; then
          if [ $MTNAME = i86pc ]; then
             SYSNAME=sunx86
          else
             case $RLNAME in 5.6) RFX=56 ;; 5.7) RFX=57 ;; 5.8) RFX=58 ;; 5.9) RFX=59 ;; esac
             SYSNAME=sun4x_$RFX
          fi
     elif [ $OSNAME = Linux ]; then
          case $RLNAME in 2.2*) RFX=22 ;; 2.4*) RFX=24 ;; esac
          SYSNAME=i386_linux$RFX
     elif [ $OSNAME = FreeBSD ]; then
          case $RLNAME in 4.2*) RFX=42 ;; 4.3*) RFX=43 ;; 4.4*) RFX=44 ;; esac
          SYSNAME=FreeBSD$RFX
     elif [ $OSNAME = AIX ]; then
          case $RLNAME in 2) RFX=42 ;; 3) RFX=43 ;; 4) RFX=44 ;; esac
          SYSNAME=rs_aix$RFX
     else
          SYSNAME=misc
       fi
  else
          SYSNAME=misc
    fi

  if FileThere d bin; then
  if FileThere d bin/$SYSNAME; then :
  else
      /bin/mkdir -p bin/$SYSNAME
      /bin/mkdir -p bin/dbg
  fi
  fi
  if FileThere d lib; then
  if FileThere d lib/$SYSNAME; then :
  else
      /bin/mkdir -p lib/$SYSNAME
      /bin/mkdir -p lib/dbg
  fi
  fi
  if FileThere d obj; then
  if FileThere d obj/$SYSNAME; then :
  else
      /bin/mkdir -p obj/$SYSNAME
      /bin/mkdir -p obj/$SYSNAME/dbg
  fi
  fi

  echo $SYSNAME
