# This file was automatically generated by SWIG
package XrdClientAdmin;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package XrdClientAdminc;
bootstrap XrdClientAdmin;
package XrdClientAdmin;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package XrdClientAdmin;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package XrdClientAdmin;

*XrdCA_Initialize = *XrdClientAdminc::XrdCA_Initialize;
*XrdCA_Terminate = *XrdClientAdminc::XrdCA_Terminate;
*XrdCA_SysStatX = *XrdClientAdminc::XrdCA_SysStatX;
*XrdCA_ExistFiles = *XrdClientAdminc::XrdCA_ExistFiles;
*XrdCA_ExistDirs = *XrdClientAdminc::XrdCA_ExistDirs;
*XrdCA_IsFileOnline = *XrdClientAdminc::XrdCA_IsFileOnline;
*XrdCA_Mv = *XrdClientAdminc::XrdCA_Mv;
*XrdCA_Mkdir = *XrdClientAdminc::XrdCA_Mkdir;
*XrdCA_Chmod = *XrdClientAdminc::XrdCA_Chmod;
*XrdCA_Rm = *XrdClientAdminc::XrdCA_Rm;
*XrdCA_Rmdir = *XrdClientAdminc::XrdCA_Rmdir;
*XrdCA_Prepare = *XrdClientAdminc::XrdCA_Prepare;
*XrdCA_DirList = *XrdClientAdminc::XrdCA_DirList;
*XrdCA_GetChecksum = *XrdClientAdminc::XrdCA_GetChecksum;

# ------- VARIABLE STUBS --------

package XrdClientAdmin;

1;
