#!/bin/sh
#
#  $Id$
#
# (C) 2005 by the Board of Trustees of the Leland Stanford, Jr., University
#                          All Rights Reserved
# Produced by Andrew Hanushevsky for Stanford University under contract
#            DE-AC03-76-SFO0515 with the Deprtment of Energy

# Syntax: StartCMS [-c cfile] [-D] [oth] [-v] [ver]

# Where:  -c  specifies the configuration file to be used.
#         -d  passes the -d option to cmsd
#         -D  turns on internal debugging.
#         -t  types the commands and does not execute them
#         -v  produces verbose output.
#         oth Any other single letter options to be passed to the executable.

#        ver  is version number to use. This is the string that is put in
#             $CMSBASE/<ver>/bin, the default is prod.
#
# Set default values
#
. $0.cf

VERBOSE=0
# Set TEST to equal /bin/echo to only display lines to be executed
#
TEST=

umask 002

##############################################################################
#                           s u b r o u t i n e s                            #
##############################################################################

Debug () {
    if test $VERBOSE -eq 1; then
       /bin/echo $1
    fi
    }
  
MustExist () {
    Debug "Checking existence of $1 $3 ..."
    if test ! -${2} $3 ; then
       Notify "$1 $3 not found."
    fi
    }

Writable () {
    Debug "Checking writability of $1 $2 ..."
    if test -r $2 ; then
       if test ! -w $2 ; then
          Notify "$1 $2 is not writable by $MYNAME."
       fi
    fi
    }
  
Wait4File () {
    Debug "Checking file $2 ..."
    tcnt=$count
    until test -${1} $2 -o $tcnt -eq 0; do
          /bin/echo StartCMS: File $2 not found\; waiting $time seconds...
          /bin/sleep $time
          tcnt=`/usr/bin/expr $tcnt - 1`
    done
    if [ $tcnt -le 0 ]; then
       Notify "File $2 not found."
    fi
    }

Notify () {
    /bin/echo StartCMS: $1
    exit 4
    }

##############################################################################
#                          m a i n   p r o g r a m                           #
##############################################################################

# Pick up options
#
HAVEVER=
CMSOPTS=
CMSPARM=$*

while test -n "$1"; do
     isopt=0
     case $1 in [-]*) isopt=1;
     esac
     if [ "$isopt" = "0" -a -z "$HAVEVER" ]; then
        CMSVER=$1
        HAVEVER=1
   elif [ "$1" = "-c" ]; then
        if [ -z "$2" ]; then
           Notify "Configuration file not specified."
        fi
        if [ ! -r "$2" ]; then
           Notify "Configuration file '$2' not found."
        fi
        CMSCONFIGFN=$2
        shift
   elif [ "$1" = "-D" ]; then
        set -x
   elif [ "$1" = "-n" ]; then
        shift
        CMSOPTS="$CMSOPTS -n $1"
   elif [ "$1" = "-t" ]; then
        TEST=echo
   elif [ "$1" = "-v" ]; then
        VERBOSE=1
   else
        CMSOPTS="$CMSOPTS $1"
     fi
   shift
   done

# Establish location of the CMS executables
#
  CMSBASE=`(cd $CMSBASE/$CMSVER; pwd)`
  if [ $? != 0 ]; then
     exit 4
  fi

  CMSPROG=$CMSBASE/bin/$CMSPROG
  PROGRAM=$CMSBASE/etc/$PROGRAM
  if [ "$CMSCONFIGFN" = "" ]; then
     CMSCONFIGFN=$CMSBASE/etc/$OLBCONFIG
  fi

# Establish log file name
#
  CMSLOGFILE=$CMSLOGDIR/$CMSLOGFN
  if [ "x$CMSMODE" = "x-m -s" ]; then
     CMSLOGFILE=$CMSLOGFILE.super
  fi

# Verify that we are not executing this script as root (if we are, switch)
#
if [ $MYNAME = root ]; then
   if [ $CMSUSER != root ]; then
      $TEST exec /bin/su $CMSUSER -c "$PROGRAM $CMSPARM"
      fi
   elif [ $MYNAME != $CMSUSER ]; then
        Notify "Attempt to start $CMSUSER cmsd as user $MYNAME."
   fi

# Verify that all required directories are present
#
for FN in $CMSBASE $CMSLOGDIR $CMSHOMEDIR
    do
    MustExist Directory d $FN
done

# Verify that all owned directories are writable
#
for FN in $CMSLOGDIR $CMSHOMEDIR
    do
    Writable Directory $FN
done
  
# Verify that all required readable files are present
#
for FN in $CMSCONFIGFN
    do
    Wait4File r $FN
done
  
# Verify that all required executable files are present
#
XLIST="$CMSPROG"
for FN in $XLIST
    do
    Wait4File x $FN
done

# Set appropriate limits
#
$TEST ulimit -n $MAXFD
$TEST ulimit -c unlimited

# Add our "lib" directory to LD_LIBRARY_PATH
#
  CMSLIBBASE=$CMSBASE/lib
  if [ -z "$LD_LIBRARY_PATH" ]; then
     LD_LIBRARY_PATH=$CMSLIBBASE
     else
     LD_LIBRARY_PATH=$CMSLIBBASE:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH

# Now start the daemon
#
/bin/echo Starting cmsd ...
$TEST cd $OLBHOMEDIR
$TEST $CMSPROG $CMSOPTS $CMSMODE -l $CMSLOGFILE -c $CMSCONFIGFN &
stat=$?

# Check if we were successful
#
if test $stat -gt 0 ; then
   Notify "$CMSPROG returned a status of ${stat}."
   fi
