#!/usr/bin/env bats

bats_load_library bats-support
bats_load_library bats-assert

setup() {
  TEST_NAME=curl

  if [[ -z "$BINARY_DIR" || ! -d "$BINARY_DIR" ]]; then
    fail "BINARY_DIR does not identify a build directory"
  fi

  XRDFS_BIN="$BINARY_DIR/bin/xrdfs"
  [[ -x "$XRDFS_BIN" ]] || fail "$XRDFS_BIN is not executable"

  ENV_FILE="$BINARY_DIR/tests/$TEST_NAME/setup.sh"
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist"
  source "$ENV_FILE"

  export XRD_PLUGINCONFDIR="$BINARY_DIR/tests/$TEST_NAME/client.plugins.d"
  export X509_CERT_FILE="$X509_CA_FILE"
  export BEARER_TOKEN_FILE="$WRITE_TOKEN"
  chmod 0600 "$BEARER_TOKEN_FILE"

  # Force use of the token file generated by the CTest fixture.
  unset BEARER_TOKEN

  TAPE_FILE_PATH=/test/tape/file
  TAPE_FILE_URL="$ORIGIN_URL$TAPE_FILE_PATH"
}

archive_info() {
  curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$WRITE_TOKEN")" \
    --header "Content-Type: application/json" \
    --data "{\"paths\":[\"$TAPE_FILE_PATH\"]}" \
    "$ORIGIN_URL/api/v1/archiveinfo"
}

authenticated_cat() {
  "$XRDFS_BIN" "$ORIGIN_URL" cat "$1?authz=$(<"$READ_TOKEN")"
}

bats::on_failure() {
  local log
  for log in origin.log client.log; do
    if [[ -f "$BINARY_DIR/tests/$TEST_NAME/$log" ]]; then
      printf '\n--- %s ---\n' "$log" >&2
      cat "$BINARY_DIR/tests/$TEST_NAME/$log" >&2
    fi
  done
}

@test "xrdfs completes the Tape REST stage lifecycle" {
  run archive_info
  assert_success
  assert_output --partial '"locality":"TAPE"'

  run "$XRDFS_BIN" prepare -s --pin-lifetime 86400 "$TAPE_FILE_URL"
  assert_success
  request_id="$output"
  if [[ ! "$request_id" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
    fail "stage did not return a UUID: $request_id"
  fi

  run "$XRDFS_BIN" "$ORIGIN_URL" query prepare "$request_id"
  assert_success
  assert_output --partial "\"id\":\"$request_id\""
  assert_output --partial '"state":"COMPLETED"'
  assert_output --partial "\"path\":\"$TAPE_FILE_PATH\""

  run authenticated_cat "$TAPE_FILE_PATH"
  assert_success
  assert_output "tape contents"

  run archive_info
  assert_success
  assert_output --partial '"locality":"DISK_AND_TAPE"'

  run curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$WRITE_TOKEN")" \
    --header "Content-Type: application/json" \
    --data "{\"paths\":[\"$TAPE_FILE_PATH\",\"/test/tape/missing\"]}" \
    --output /dev/null --write-out '%{http_code}' \
    "$ORIGIN_URL/api/v1/stage/$request_id/cancel"
  assert_success
  assert_output "400"

  run "$XRDFS_BIN" prepare -a "$request_id" "$TAPE_FILE_URL"
  assert_success

  run authenticated_cat "$TAPE_FILE_PATH"
  assert_success
  assert_output "tape contents"

  run "$XRDFS_BIN" prepare -e "$request_id" "$TAPE_FILE_URL"
  assert_success

  run archive_info
  assert_success
  assert_output --partial '"locality":"TAPE"'

  run authenticated_cat "$TAPE_FILE_PATH"
  assert_failure

  run "$XRDFS_BIN" "$ORIGIN_URL" query prepare -d "$request_id"
  assert_success

  run curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$WRITE_TOKEN")" \
    --output /dev/null --write-out '%{http_code}' \
    "$ORIGIN_URL/api/v1/stage/$request_id"
  assert_success
  assert_output "404"
}

@test "xrdfs supports tape discovery and archiveinfo queries" {
  run "$XRDFS_BIN" "$ORIGIN_URL" query tape discover
  assert_success
  assert_output --partial "Tape REST Discovery:"

  run "$XRDFS_BIN" "$ORIGIN_URL" query tape --json discover
  assert_success
  assert_output --partial '"uri"'

  run "$XRDFS_BIN" "$ORIGIN_URL" query tape archiveinfo "$TAPE_FILE_URL"
  assert_success

  run "$XRDFS_BIN" "$ORIGIN_URL" query tape --json archiveinfo "$TAPE_FILE_URL"
  assert_success
  assert_output --partial '"locality"'
}

@test "xrdfs exposes GFAL Tape REST virtual attributes" {
  run "$XRDFS_BIN" xattr "$TAPE_FILE_URL"
  assert_success
  assert_line "taperestapi.version = v1"
  assert_line "taperestapi.uri = $ORIGIN_URL/api/v1"
  assert_line "taperestapi.sitename = XRootD Tape Test"

  run "$XRDFS_BIN" xattr "$TAPE_FILE_URL" taperestapi.version
  assert_success
  assert_output "v1"

  run "$XRDFS_BIN" xattr "$TAPE_FILE_URL" user.status
  assert_success
  if [[ "$output" != "NEARLINE" &&
        "$output" != "ONLINE_AND_NEARLINE" ]]; then
    fail "unexpected GFAL tape status: $output"
  fi
}

@test "xrdfs rejects unsupported Tape REST prepare flags" {
  run "$XRDFS_BIN" prepare -s -w "$TAPE_FILE_URL"
  assert_failure
}

@test "Tape REST errors use RFC 7807 responses" {
  local headers="$BATS_TEST_TMPDIR/problem.headers"
  local body="$BATS_TEST_TMPDIR/problem.json"

  run curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$WRITE_TOKEN")" \
    --header "Content-Type: application/json" \
    --data '{}' --dump-header "$headers" --output "$body" \
    --write-out '%{http_code}' "$ORIGIN_URL/api/v1/archiveinfo"
  assert_success
  assert_output "400"

  run grep -qi '^Content-Type: application/problem+json' "$headers"
  assert_success

  run grep -q '"status":400' "$body"
  assert_success
}
