#!/usr/bin/env bats

bats_load_library bats-support
bats_load_library bats-assert

setup() {
  TEST_NAME=curl

  if [[ -z "$BINARY_DIR" || ! -d "$BINARY_DIR" ]]; then
    fail "BINARY_DIR does not identify a build directory"
  fi

  XRDFS_BIN="$BINARY_DIR/bin/xrdfs"
  [[ -x "$XRDFS_BIN" ]] || fail "$XRDFS_BIN is not executable"

  ENV_FILE="$BINARY_DIR/tests/$TEST_NAME/setup.sh"
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist"
  source "$ENV_FILE"

  # Start each test with a clean mock control file.
  rm -f "$TAPE_API_ROOT/control.json"

  export XRD_PLUGINCONFDIR="$BINARY_DIR/tests/$TEST_NAME/client.plugins.d"
  export X509_CERT_FILE="$X509_CA_FILE"
  export BEARER_TOKEN_FILE="$READ_TOKEN"
  chmod 0600 "$BEARER_TOKEN_FILE"

  # Force use of the token file generated by the CTest fixture.
  unset BEARER_TOKEN

  TAPE_FILE_PATH=/test/tape/file
  TAPE_FILE_URL="$ORIGIN_URL$TAPE_FILE_PATH"
}

archive_info() {
  curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$READ_TOKEN")" \
    --header "Content-Type: application/json" \
    --data "{\"paths\":[\"$TAPE_FILE_PATH\"]}" \
    "$ORIGIN_URL/api/v1/archiveinfo"
}

authenticated_cat() {
  "$XRDFS_BIN" "$ORIGIN_URL" cat "$1?authz=$(<"$READ_TOKEN")"
}


poll_prepare() {
  local response
  for ((attempt=0; attempt<60; ++attempt)); do
    response=$("$XRDFS_BIN" "$ORIGIN_URL" query prepare "$1") || return $?
    if [[ "$response" == *'"state":"COMPLETED"'* ]]; then
      printf '%s\n' "$response"
      return 0
    fi
    if [[ "$response" == *'"state":"FAILED"'* || "$response" == *'"state":"CANCELLED"'* ]]; then
      printf '%s\n' "$response"
      return 1
    fi
    sleep 1
  done
  printf '%s\n' "$response"
  return 1
}

poll_locality() {
  local response
  for ((attempt=0; attempt<60; ++attempt)); do
    response=$(archive_info) || return $?
    if [[ "$response" == *"\"locality\":\"$1\""* ]]; then
      printf '%s\n' "$response"
      return 0
    fi
    sleep 1
  done
  printf '%s\n' "$response"
  return 1
}

mock_control() {
  printf '%s' "$1" > "$TAPE_API_ROOT/control.json.tmp"
  mv -f "$TAPE_API_ROOT/control.json.tmp" "$TAPE_API_ROOT/control.json"
}

restart_origin() {
  local i

  if [[ -n "$ORIGIN_PID" ]] && kill -0 "$ORIGIN_PID" 2>/dev/null; then
    kill -9 "$ORIGIN_PID" 2>/dev/null
    for i in $(seq 1 50); do
      kill -0 "$ORIGIN_PID" 2>/dev/null || break
      sleep 0.1
    done
  fi

  : > "$ORIGIN_LOG"
  (
    if [[ -d /dev/fd ]]; then
      for fd in /dev/fd/*; do
        n="${fd##*/}"
        if [[ "$n" =~ ^[0-9]+$ ]] && [[ "$n" -ge 3 ]]; then
          eval "exec $n>&-" 2>/dev/null || true
        fi
      done
    fi
    for fd in {3..64}; do
      eval "exec $fd>&-" 2>/dev/null || true
    done
    exec "$ORIGIN_WRAPPER" -n origin -c "$ORIGIN_CONFIG" </dev/null >>"$ORIGIN_LOG" 2>&1
  ) &
  ORIGIN_PID=$!

  # Record the new PID so the CTest fixture teardown stops this process.
  sed -i.bak "s/^ORIGIN_PID=.*/ORIGIN_PID=$ORIGIN_PID/" "$ENV_FILE"
  rm -f "$ENV_FILE.bak"

  for i in $(seq 1 50); do
    if grep -qa "initialization completed" "$ORIGIN_LOG"; then
      return 0
    fi
    if ! kill -0 "$ORIGIN_PID" 2>/dev/null; then
      return 1
    fi
    sleep 1
  done
  return 1
}

bats::on_failure() {
  local log
  for log in origin.log client.log; do
    if [[ -f "$BINARY_DIR/tests/$TEST_NAME/$log" ]]; then
      printf '\n--- %s ---\n' "$log" >&2
      cat "$BINARY_DIR/tests/$TEST_NAME/$log" >&2
    fi
  done
}

@test "xrdfs completes the Tape REST stage lifecycle" {
  run archive_info
  assert_success
  assert_output --partial '"locality":"TAPE"'

  run "$XRDFS_BIN" prepare -s "$TAPE_FILE_URL"
  assert_success
  request_id="$output"
  if [[ ! "$request_id" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
    fail "stage did not return a UUID: $request_id"
  fi

  run poll_prepare "$request_id"
  assert_success
  assert_output --partial "\"id\":\"$request_id\""
  assert_output --partial '"state":"COMPLETED"'
  assert_output --partial "\"path\":\"$TAPE_FILE_PATH\""

  run authenticated_cat "$TAPE_FILE_PATH"
  assert_success
  assert_output "tape contents"

  run archive_info
  assert_success
  assert_output --partial '"locality":"DISK_AND_TAPE"'

  run curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$READ_TOKEN")" \
    --header "Content-Type: application/json" \
    --data "{\"paths\":[\"$TAPE_FILE_PATH\",\"/test/tape/missing\"]}" \
    --output /dev/null --write-out '%{http_code}' \
    "$ORIGIN_URL/api/v1/stage/$request_id/cancel"
  assert_success
  assert_output "400"

  run "$XRDFS_BIN" prepare -a "$request_id" "$TAPE_FILE_URL"
  assert_success

  run authenticated_cat "$TAPE_FILE_PATH"
  assert_success
  assert_output "tape contents"

  run "$XRDFS_BIN" prepare -e "$request_id" "$TAPE_FILE_URL"
  assert_success

  run poll_locality TAPE
  assert_success
  assert_output --partial '"locality":"TAPE"'

  run authenticated_cat "$TAPE_FILE_PATH"
  assert_failure

  run curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$READ_TOKEN")" \
    --request DELETE --output /dev/null --write-out '%{http_code}' \
    "$ORIGIN_URL/api/v1/stage/$request_id"
  assert_success
  assert_output "200"

  run curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$READ_TOKEN")" \
    --output /dev/null --write-out '%{http_code}' \
    "$ORIGIN_URL/api/v1/stage/$request_id"
  assert_success
  assert_output "404"
}

@test "xrdfs rejects unsupported Tape REST prepare flags" {
  run "$XRDFS_BIN" prepare -s -w "$TAPE_FILE_URL"
  assert_failure
}

@test "Tape REST errors use RFC 7807 responses" {
  local headers="$BATS_TEST_TMPDIR/problem.headers"
  local body="$BATS_TEST_TMPDIR/problem.json"

  run curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$READ_TOKEN")" \
    --header "Content-Type: application/json" \
    --data '{}' --dump-header "$headers" --output "$body" \
    --write-out '%{http_code}' "$ORIGIN_URL/api/v1/archiveinfo"
  assert_success
  assert_output "400"

  run grep -qi '^Content-Type: application/problem+json' "$headers"
  assert_success

  run grep -q '"status":400' "$body"
  assert_success
}

@test "xrdfs stage recovers from a lost backend acknowledgement" {
  mock_control '{"failAfterAccept": true}'

  run "$XRDFS_BIN" prepare -s "$TAPE_FILE_URL"
  assert_success
  request_id="$output"

  run poll_prepare "$request_id"
  assert_success
  assert_output --partial '"state":"COMPLETED"'

  mock_control '{}'
}

@test "xrdfs stage recovers after the origin restarts" {
  mock_control '{"queryFailure": true}'

  run "$XRDFS_BIN" prepare -s "$TAPE_FILE_URL"
  assert_success
  request_id="$output"

  run "$XRDFS_BIN" "$ORIGIN_URL" query prepare "$request_id"
  assert_success
  assert_output --partial '"state":"SUBMITTED"'

  restart_origin || fail "could not restart the origin"

  mock_control '{}'

  run poll_prepare "$request_id"
  assert_success
  assert_output --partial '"state":"COMPLETED"'

  mock_control '{}'
}
