#!/usr/bin/env bats

bats_load_library bats-support
bats_load_library bats-assert

setup() {
  TEST_NAME=curl

  if [[ -z "$BINARY_DIR" || ! -d "$BINARY_DIR" ]]; then
    fail "BINARY_DIR does not identify a build directory"
  fi

  XRDFS_BIN="$BINARY_DIR/bin/xrdfs"
  [[ -x "$XRDFS_BIN" ]] || fail "$XRDFS_BIN is not executable"

  ENV_FILE="$BINARY_DIR/tests/$TEST_NAME/setup.sh"
  [[ -f "$ENV_FILE" ]] || fail "$ENV_FILE does not exist"
  source "$ENV_FILE"

  export XRD_PLUGINCONFDIR="$BINARY_DIR/tests/$TEST_NAME/client.plugins.d"
  export X509_CERT_FILE="$X509_CA_FILE"
  export BEARER_TOKEN_FILE="$WRITE_TOKEN"
  chmod 0600 "$BEARER_TOKEN_FILE"

  # Force use of the token file generated by the CTest fixture.
  unset BEARER_TOKEN

  TAPE_FILE_URL="$ORIGIN_URL/store/file"
}

bats::on_failure() {
  local log
  for log in origin.log client.log; do
    if [[ -f "$BINARY_DIR/tests/$TEST_NAME/$log" ]]; then
      printf '\n--- %s ---\n' "$log" >&2
      cat "$BINARY_DIR/tests/$TEST_NAME/$log" >&2
    fi
  done
}

@test "xrdfs completes the Tape REST stage lifecycle" {
  run "$XRDFS_BIN" prepare -s "$TAPE_FILE_URL"
  assert_success
  assert_output "request-1"

  run "$XRDFS_BIN" "$ORIGIN_URL" query prepare request-1
  assert_success
  assert_output --partial '"id":"request-1"'
  assert_output --partial '"state":"COMPLETED"'

  run "$XRDFS_BIN" prepare -a request-1 "$TAPE_FILE_URL"
  assert_success

  run "$XRDFS_BIN" prepare -e request-1 "$TAPE_FILE_URL"
  assert_success
}

@test "xrdfs rejects unsupported Tape REST prepare flags" {
  run "$XRDFS_BIN" prepare -s -w "$TAPE_FILE_URL"
  assert_failure
}

@test "Tape REST errors use RFC 7807 responses" {
  local headers="$BATS_TEST_TMPDIR/problem.headers"
  local body="$BATS_TEST_TMPDIR/problem.json"

  run curl --silent --show-error --cacert "$X509_CA_FILE" \
    --header "Authorization: Bearer $(<"$WRITE_TOKEN")" \
    --header "Content-Type: application/json" \
    --data '{}' --dump-header "$headers" --output "$body" \
    --write-out '%{http_code}' "$ORIGIN_URL/api/v1/archiveinfo"
  assert_success
  assert_output "400"

  run grep -qi '^Content-Type: application/problem+json' "$headers"
  assert_success

  run grep -q '"status":400' "$body"
  assert_success
}
