.TH xrd 1 "@CMAKE_INSTALL_DATE@" "Version @XrdVERSIONSTR@" "xrootd"
.SH NAME
xrd \- XRootD command-line client
.SH SYNOPSIS
.B xrd
[
.I options
]
.SH DESCRIPTION
.B xrd
is the XRootD command-line client.
.SH OPTIONS
.TP
.B --version
Display version information and exit.
.SH STAT
.B xrd stat
prints file metadata for local paths, file URLs, and XRootD URLs.
