.TH xrdfs 1 "30 November 2011"
.SH NAME
xrdfs - xrootd file and directory meta-data utility
.SH SYNOPSIS
.nf

\fBxrdfs\fR \fIhost[:port]\fR \fI[command [args]]\fR

\fBcommand\fR: help, chmod, locate, mkdir, mv, stat, statvfs, query, rm ,rmdir,
         truncate
.fi
.br
.ad l
.SH DESCRIPTION
The \fBxrdfs\fR utility executes meta-data oriented operations
(e.g., ls, mv, rm, etc.) on one or more xrootd servers.
Command help is available by invoking \fBxrdfs\fR with no command
line options or parameters and then typing "help" in response to the
input prompt.

.SH COMMANDS
\fBchmod\fR \fIpath\fR \fI<user><group><other>\fR
.RS 3
Modify permissions of the \fIpath\fR. Permission string example:
\fIrwxr-x--x\fR

.RE
\fBls\fR \fI[-l]\fR \fI[-u]\fR \fI[dirname]\fR
.RS 3
Get directory listing.
.br
\fI-l\fR stat every entry and pring long listing
.br
\fI-u\fR print paths as URLs

.RE
\fBlocate\fR \fI[-n]\fR \fI[-r]\fR \fI[-d]\fR \fI<path>\fR
.RS 3
Get the locations of the path.
.br
\fI-r\fR refresh, don't use cached locations
.br
\fI-n\fR make the server return the response immediately even though it may be incomplete
.br
\fI-d\fR do a recursive, deep locate in order to find data servers
.br
\fI-m\fR prefer host names to IP addresses

.RE
\fBmkdir\fR \fI[-p] [-m<user><group><other>] <dirname>\fR
.RS 3
Creates a directory/tree of directories.
.br
\fI-p\fR create the entire directory tree recursively
.br
\fI-m\fR\fB<user><group><other>\fR permissions for newly created directories

.RE
\fBmv\fR \fI<path1> <path2>\fR
.RS 3
Move path1 to path2 locally on the same server.

.RE
\fBstat\fR \fI<path>\fR
.RS 3
Get info about the file or directory.
.br
\fI-q\fR query optional flag query parameter that makes
xrdfs return error code to the shell if the
requested flag combination is not present;
flags may be combined together using '|' or '&'
.br
Available flags:
\fBXBitSet\fR, \fBIsDir\fR, \fBOther\fR, \fBOffline\fR, \fBPOSCPending\fR,
\fBIsReadable\fR, \fBIsWriteable\fR

.RE
\fBstatvfs\fR \fI<path>\fR
.RS 3
Get info about a virtual file system.

.RE
\fBquery\fR \fI<code> <params>\fR
.RS 3
Obtain server information. Query codes:
.br
\fIconfig\fR         \fB<what>\fR   Server configuration
.br
\fIchecksumcancel\fR \fB<path>\fR   File checksum cancelation
.br
\fIchecksum\fR       \fB<path>\fR   File checksum
.br
\fIopaque\fR         \fB<arg>\fR    Implementation dependent
.br
\fIopaquefile\fR     \fB<arg>\fR    Implementation dependent
.br
\fIspace\fR          \fB<space>\fR  Logical space stats
.br
\fIstats\fR          \fB<what>\fR   Server stats; <what> is a list of letters
indicating information to be returned:
.RS 5
a - all statistics
.br
p - protocol statistics
.br
b - buffer usage statistics
.br
s - scheduling statistics
.br
d - device polling statistics
.br
u - usage statistics
.br
i - server identification
.br
z - synchronized statistics
.br
l - connection statistics
.br
.RE
\fIxattr\fR          \fB<path>\fR   Extended attributes

.RE
\fBrm\fR \fI<filename>\fR
.RS 3
Remove a file.

.RE
\fBrmdir\fR \fI<dirname>\fR
.RS 3
Remove a directory.

.RE
\fBtruncate\fR \fI<filename> <length>\fR
.RS 3
Truncate a file.

.RE
\fBprepare\fR \fI[-c]\fR \fI[-f]\fR \fI[-s]\fR \fI[-w]\fR \fI[-p priority]\fR \fIfilenames\fR
.RS 3
Prepare one or more files for access.
.br
\fI-c\fR co-locate staged files if possible
.br
\fI-f\fR refresh file access time even if the location is known
.br
\fI-s\fR stage the files to disk if they are not online
.br
\fI-w\fR whe files will be accessed for modification
.br
\fI-p\fR priority of the request, 0 (lowest) - 3 (highest)

.SH NOTES
For the list of available environment variables please refere to xrdcopy(1)

.SH DIAGNOSTICS
Errors yield an error message and a non-zero exit status.

.SH LICENSE
LGPL

.SH SUPPORT LEVEL
The \fBxrdfs\fR command is supported by the XRootD Collaboration.
Contact information can be found at

.ce
http://xrootd.org/contact.html
