.TH xrootdfs 8 "8 March 2011"
.SH NAME
xrootdfs - xrootd FUSE file system daemon
.SH SYNOPSIS
.nf

\fBxrootdfs\fR [\fIoptions\fR] \fIparameters\fR

.fi
.br
.ad l
.SH DESCRIPTION
The \fBxrootdfs\fR daemon provides a file system view of an xrootd cluster
using FUSE.
Usage synopsis can be displayed by typing "\fBxrootdfs -h\fR".
Short documentation can be found in a README file in the src/XrdFfs source
directory.
.SH NOTES
Documentation for all components associated with \fBxrootdfs\fR can be found at
http://xrootd.org/docs.html
.SH DIAGNOSTICS
Errors yield an error message and a non-zero exit status.
The program never exits upon success.  Use the umount command to terminate the
program.

Additional logging information can be found in syslog (/var/log/messages)
.SH EXAMPLES
Assuming the redirector is 
.B rdr:port

use in /etc/fstab
.RS
xrootdfs /mnt fuse rdr=root://rdr:port//data,uid=daemon 1 2
.RE

use with autofs
.RS
1. add a line to /etc/auto.master
.RE
.RS
/\- /etc/auto.fuse

2. create /etc/auto.fuse with the following one line
.RE
.RS
/mnt \-fstype=fuse,uid=2,rdr=root://rdr\\:port//data :xrootdfs.sh

3. create script /usr/bin/xrootdfs.sh (make sure +x bit is set)
.RE
.RS
#!/bin/sh
.RS
.RE
exec /usr/bin/xrootdfs $@ >/dev/null 2>&1
.SH LICENSE
License terms can be displayed by typing "\fBxrootd -H\fR".
.SH SUPPORT LEVEL
The \fBxrootdfs\fR daemon is supported by the xrootd collaboration.
Contact information can be found at
.ce
http://xrootd.org/contact.html
