include( FindPackageHandleStandardArgs )

if( READLINE_INCLUDE_DIR AND READLINE_LIBRARY AND NCURSES_LIBRARY )
  set( READLINE_FOUND TRUE )
else( READLINE_INCLUDE_DIR AND READLINE_LIBRARY AND NCURSES_LIBRARY )
  find_path( READLINE_INCLUDE_DIR readline/readline.h /usr/include/readline )

  find_library( READLINE_LIBRARY NAMES readline )
  find_library( NCURSES_LIBRARY  NAMES ncurses  )

  find_package_handle_standard_args(
    READLINE
    DEFAULT_MSG
    READLINE_LIBRARY READLINE_INCLUDE_DIR NCURSES_LIBRARY )

  mark_as_advanced( READLINE_INCLUDE_DIR READLINE_LIBRARY )
endif( READLINE_INCLUDE_DIR AND READLINE_LIBRARY AND NCURSES_LIBRARY )
