
FIND_PATH(SCITOKENS_CPP_INCLUDE_DIR scitokens/scitokens.h
  HINTS
  ${SCITOKENS_CPP_DIR}
  $ENV{SCITOKENS_CPP_DIR}
  /usr
  PATH_SUFFIXES include
)

FIND_LIBRARY(SCITOKENS_CPP_LIBRARIES SciTokens
  HINTS
  ${SCITOKENS_CPP_DIR}
  $ENV{SCITOKENS_CPP_DIR}
  /usr
  PATH_SUFFIXES lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SciTokensCpp DEFAULT_MSG SCITOKENS_CPP_LIBRARIES SCITOKENS_CPP_INCLUDE_DIR)

