FIND_PATH(TINYXML_INCLUDE_DIR tinyxml.h
  HINTS
  ${TINYXML_DIR}
  $ENV{TINYXML_DIR}
  /usr
  PATH_SUFFIXES include
)

FIND_LIBRARY(TINYXML_LIBRARIES tinyxml
  HINTS
  ${TINYXML_DIR}
  $ENV{TINYXML_DIR}
  /usr
  PATH_SUFFIXES lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TinyXml DEFAULT_MSG TINYXML_LIBRARIES TINYXML_INCLUDE_DIR)
