#!/usr/bin/env bash
#
# BATS formatter that writes a CDash Test.xml report.
#
# CDash attaches the report to the build with the Site attributes. Set
# CDASH_SITE, CDASH_BUILD_NAME, and CDASH_BUILD_STAMP to the values of the
# CTest build. Without them, CDash creates a separate build for the report.

set -e
trap '' INT

# shellcheck source=lib/bats-core/formatter.bash
source "$BATS_ROOT/$BATS_LIBDIR/bats-core/formatter.bash"

declare -a case_name case_status case_ms case_path case_file case_output

declare -r base_path="$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
declare -r command_line="$(tr '\0' ' ' < "/proc/$PPID/cmdline" 2>/dev/null)"

count=0
current=0
current_path='.'
current_file=''
start_epoch=$(date +%s)
start_human=$(date '+%b %d %H:%M %Z')

site_name="${CDASH_SITE:-$(uname -n)}"
build_name="${CDASH_BUILD_NAME:-$(uname -s)-$(uname -m)}"
build_stamp="${CDASH_BUILD_STAMP:-$(date '+%Y%m%d-%H%M')-Experimental}"

xml_escape() { # <text> -> XML-escaped text on stdout
  local text=$1
  # Escape '&' in each replacement: bash 5.2 expands a bare '&' to the match.
  text=${text//&/\&amp;}
  text=${text//</\&lt;}
  text=${text//>/\&gt;}
  text=${text//\"/\&quot;}
  printf '%s' "$text"
}

print_report() {
  local end_epoch i name path
  end_epoch=$(date +%s)

  printf '<?xml version="1.0" encoding="UTF-8"?>\n'
  printf '<Site BuildName="%s" BuildStamp="%s" Name="%s" Generator="bats-format-cdash">\n' \
    "$(xml_escape "$build_name")" "$(xml_escape "$build_stamp")" "$(xml_escape "$site_name")"
  printf '\t<Testing>\n'
  printf '\t\t<StartDateTime>%s</StartDateTime>\n' "$start_human"
  printf '\t\t<StartTestTime>%s</StartTestTime>\n' "$start_epoch"

  printf '\t\t<TestList>\n'
  for ((i = 1; i <= count; i++)); do
    printf '\t\t\t<Test>%s</Test>\n' \
      "$(xml_escape "${case_path[i]}/${case_file[i]} ${case_name[i]}")"
  done
  printf '\t\t</TestList>\n'

  for ((i = 1; i <= count; i++)); do
    name=$(xml_escape "${case_file[i]} ${case_name[i]}")
    path=$(xml_escape "${case_path[i]}")
    printf -v seconds '%g' "${case_ms[i]}e-3" # milliseconds -> seconds

    printf '\t\t<Test Status="%s">\n' "${case_status[i]}"
    printf '\t\t\t<Name>%s</Name>\n' "$name"
    printf '\t\t\t<Path>%s</Path>\n' "$path"
    printf '\t\t\t<FullName>%s/%s</FullName>\n' "$path" "$name"
    printf '\t\t\t<FullCommandLine>%s</FullCommandLine>\n' "$(xml_escape "$command_line")"
    printf '\t\t\t<Results>\n'
    printf '\t\t\t\t<NamedMeasurement type="numeric/double" name="Execution Time">\n'
    printf '\t\t\t\t\t<Value>%s</Value>\n' "$seconds"
    printf '\t\t\t\t</NamedMeasurement>\n'
    printf '\t\t\t\t<NamedMeasurement type="text/string" name="Completion Status">\n'
    printf '\t\t\t\t\t<Value>Completed</Value>\n'
    printf '\t\t\t\t</NamedMeasurement>\n'
    printf '\t\t\t\t<NamedMeasurement type="text/string" name="Command Line">\n'
    printf '\t\t\t\t\t<Value>%s</Value>\n' "$(xml_escape "$command_line")"
    printf '\t\t\t\t</NamedMeasurement>\n'
    printf '\t\t\t\t<Measurement>\n'
    if [[ -z "${case_output[i]}" ]]; then
      printf '\t\t\t\t\t<Value></Value>\n'
    else
      # CDash decompresses the value with zlib, not with the gzip file format.
      printf '\t\t\t\t\t<Value encoding="base64" compression="gzip">%s</Value>\n' \
        "$(printf '%s' "${case_output[i]}" | openssl zlib -e | base64)"
    fi
    printf '\t\t\t\t</Measurement>\n'
    printf '\t\t\t</Results>\n'
    printf '\t\t</Test>\n'
  done

  printf '\t\t<EndDateTime>%s</EndDateTime>\n' "$(date '+%b %d %H:%M %Z')"
  printf '\t\t<EndTestTime>%s</EndTestTime>\n' "$end_epoch"
  printf '\t\t<ElapsedMinutes>%s</ElapsedMinutes>\n' "$(((end_epoch - start_epoch) / 60))"
  printf '\t</Testing>\n'
  printf '</Site>\n'
}

trap print_report EXIT

bats_tap_stream_plan() {
  :
}

bats_tap_stream_suite() { # <file>
  local file="$(realpath "$1")"
  file="${file#"$base_path"/}"
  current_path=$(dirname "$file")
  current_file=$(basename "$file" .bats)
}

bats_tap_stream_begin() { # <index>
  current="$1"
  ((count < current)) && count="$current"
  case_path[current]="$current_path"
  case_file[current]="$current_file"
  case_name[current]=''
  case_status[current]='notrun'
  case_ms[current]=0
  case_output[current]=''
  return 0
}

bats_tap_stream_ok() { # <index> <name>
  case_name[$1]="$2"
  case_status[$1]='passed'
  case_ms[$1]="${BATS_FORMATTER_TEST_DURATION:-0}"
}

bats_tap_stream_skipped() { # <index> <name> <reason>
  case_name[$1]="$2"
  case_status[$1]='notrun'
  case_output[$1]="Skipped${3:+: $3}"
}

bats_tap_stream_not_ok() { # <index> <name>
  case_name[$1]="$2"
  case_status[$1]='failed'
  case_ms[$1]="${BATS_FORMATTER_TEST_DURATION:-0}"
}

bats_tap_stream_comment() { # <text>
  case_output[current]+="$1"$'\n'
}

bats_tap_stream_unknown() { # <line>
  case_output[current]+="$1"$'\n'
}

bats_parse_internal_extended_tap
